framework:
    messenger:
        serializer:
          default_serializer: messenger.transport.symfony_serializer
          symfony_serializer:
            format: json
            context: { }

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            singlecompute-get:
              dsn: "%env(KAFKA_SINGLECOMPUTE_URL)%"
              retry_strategy:
                max_retries: 0
              options:
                commitAsync: '%env(bool:KAFKA_SINGLECOMPUTE_COMMIT_ASYNC)%'
                receiveTimeout: '%env(int:KAFKA_SINGLECOMPUTE_RECEIVE_TIMEOUT)%'
                topic:
                  name: '%env(KAFKA_SINGLECOMPUTE_COLLECT_TOPIC)%'
                kafka_conf:
                  group.id: '%env(KAFKA_SINGLECOMPUTE_COMPUTE_GROUPE_ID)%'
                  # consumer
                  enable.auto.offset.store: '%env(KAFKA_SINGLECOMPUTE_ENABLE_AUTO_OFFSET_STORE)%'
                  socket.keepalive.enable: '%env(KAFKA_SINGLECOMPUTE_SOCKET_KEEPALIVE_ENABLE)%'
                  metadata.max.age.ms: '%env(KAFKA_SINGLECOMPUTE_METADATA_MAX_AGE_MS)%'
                  heartbeat.interval.ms: '%env(KAFKA_SINGLECOMPUTE_HEARTBEAT_INTERVAL_MS)%'
                  session.timeout.ms: '%env(KAFKA_SINGLECOMPUTE_SESSION_TIMEOUT_MS)%'
                  # connection
                  sasl.username: '%env(KAFKA_SINGLECOMPUTE_SASL_USERNAME)%'
                  sasl.password: '%env(KAFKA_SINGLECOMPUTE_SASL_PASSWORD)%'
                  security.protocol: '%env(KAFKA_SINGLECOMPUTE_SECURITY_PROTOCOL)%'
                  sasl.mechanism: '%env(KAFKA_SINGLECOMPUTE_SASL_MECHANISM)%'
                  bootstrap.servers: '%env(KAFKA_SINGLECOMPUTE_BOOTSTRAP_SERVERS)%'
                topic_conf:
                  request.timeout.ms: '%env(KAFKA_SINGLECOMPUTE_REQUEST_TIME_MS)%'
                  acks: '%env(KAFKA_SINGLECOMPUTE_ACKS)%'
                  auto.offset.reset: '%env(KAFKA_SINGLECOMPUTE_AUTO_OFFSET_RESET)%'
  
            singlecompute-produce:
              dsn: "%env(KAFKA_SINGLECOMPUTE_URL)%"
              retry_strategy:
                max_retries: 0
              options:
                flushTimeout: '%env(int:KAFKA_SINGLECOMPUTE_FLUSH_TIMEOUT)%'
                topic:
                  name: '%env(KAFKA_SINGLECOMPUTE_COMPUTE_TOPIC)%'
                kafka_conf:
                  # producer
                  socket.keepalive.enable: '%env(KAFKA_SINGLECOMPUTE_SOCKET_KEEPALIVE_ENABLE)%'
                  metadata.max.age.ms: '%env(KAFKA_SINGLECOMPUTE_METADATA_MAX_AGE_MS)%'
                  retries: '%env(KAFKA_SINGLECOMPUTE_RETRIES)%'
                  request.timeout.ms: '%env(KAFKA_SINGLECOMPUTE_REQUEST_TIME_MS)%'
                  partitioner: '%env(KAFKA_SINGLECOMPUTE_PARTITIONER)%'
                  compression.codec: '%env(KAFKA_SINGLECOMPUTE_COMPRESSION_CODED)%'
                  # connection
                  sasl.username: '%env(KAFKA_SINGLECOMPUTE_SASL_USERNAME)%'
                  sasl.password: '%env(KAFKA_SINGLECOMPUTE_SASL_PASSWORD)%'
                  security.protocol: '%env(KAFKA_SINGLECOMPUTE_SECURITY_PROTOCOL)%'
                  sasl.mechanism: '%env(KAFKA_SINGLECOMPUTE_SASL_MECHANISM)%'
                  bootstrap.servers: '%env(KAFKA_SINGLECOMPUTE_BOOTSTRAP_SERVERS)%'
                topic_conf:
                  request.timeout.ms: '%env(KAFKA_SINGLECOMPUTE_REQUEST_TIME_MS)%'
                  acks: '%env(KAFKA_SINGLECOMPUTE_ACKS)%'
                  auto.offset.reset: '%env(KAFKA_SINGLECOMPUTE_AUTO_OFFSET_RESET)%'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            App\SingleCompute\Message\ComputeOutputMessage: singlecompute-produce
